"""
PDF Report Generator
Generates PDF reports for scan results
"""

import logging
from io import BytesIO
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

from intelligence.reasoning import ReasoningEngine

logger = logging.getLogger('dr_ssm_eye')


class PDFGenerator:
    """Generate PDF reports"""
    
    def __init__(self):
        self.reasoning_engine = ReasoningEngine()
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
    
    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=12,
            spaceBefore=12
        ))
        
        self.styles.add(ParagraphStyle(
            name='CustomBody',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12
        ))
    
    def generate_per_url_report(self, scan_data: Dict[str, Any]) -> bytes:
        """
        Generate detailed PDF report for single URL
        
        Args:
            scan_data: Scan result dictionary
        
        Returns:
            PDF bytes
        """
        try:
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            story = []
            
            story.append(Paragraph("Dr. SSM Eye", self.styles['CustomTitle']))
            story.append(Paragraph("URL Analysis Report", self.styles['CustomHeading']))
            story.append(Spacer(1, 0.3*inch))
            
            classification = scan_data.get('classification', 'UNKNOWN')
            confidence = scan_data.get('confidence', 0)
            risk_score = scan_data.get('risk_score', 0)
            url = scan_data.get('url', 'N/A')
            timestamp = scan_data.get('last_scanned', datetime.now())
            
            story.append(Paragraph(f"<b>URL:</b> {url}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Classification:</b> {classification}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Confidence:</b> {confidence:.1f}%", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Risk Score:</b> {risk_score}/200", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Scanned:</b> {timestamp}", self.styles['CustomBody']))
            story.append(Spacer(1, 0.3*inch))
            
            story.append(Paragraph("Analysis", self.styles['CustomHeading']))
            
            reasoning = scan_data.get('reasoning', [])
            if reasoning:
                reasoning_text = self.reasoning_engine.format_reasoning_for_pdf(
                    [type('obj', (object,), r) for r in reasoning],
                    classification
                )
                for line in reasoning_text.split('\n'):
                    if line.strip():
                        story.append(Paragraph(line, self.styles['CustomBody']))
            else:
                story.append(Paragraph("No specific indicators found.", self.styles['CustomBody']))
            
            story.append(Spacer(1, 0.3*inch))
            story.append(Paragraph("Technical Details", self.styles['CustomHeading']))
            
            features = scan_data.get('features', {})
            if features:
                ip_address = features.get('ip_reputation_ip', 'N/A')
                domain_age = features.get('whois_domain_age_days', 'N/A')
                has_https = features.get('ssl_has_https', False)
                
                story.append(Paragraph(f"<b>IP Address:</b> {ip_address}", self.styles['CustomBody']))
                story.append(Paragraph(f"<b>Domain Age:</b> {domain_age} days", self.styles['CustomBody']))
                story.append(Paragraph(f"<b>HTTPS:</b> {'Yes' if has_https else 'No'}", self.styles['CustomBody']))
            
            story.append(Spacer(1, 0.5*inch))
            story.append(Paragraph("Generated by Dr. SSM Eye", self.styles['CustomBody']))
            
            doc.build(story)
            
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info(f"Generated PDF report for {url}")
            return pdf_bytes
        
        except Exception as e:
            logger.error(f"PDF generation error: {e}")
            raise
    
    def generate_batch_summary_report(self, scan_results: List[Dict[str, Any]]) -> bytes:
        """
        Generate batch summary report
        
        Args:
            scan_results: List of scan result dictionaries
        
        Returns:
            PDF bytes
        """
        try:
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            story = []
            
            story.append(Paragraph("Dr. SSM Eye", self.styles['CustomTitle']))
            story.append(Paragraph("Batch Scan Summary", self.styles['CustomHeading']))
            story.append(Spacer(1, 0.3*inch))
            
            total = len(scan_results)
            clean = sum(1 for r in scan_results if r.get('classification') == 'CLEAN')
            suspicious = sum(1 for r in scan_results if r.get('classification') == 'SUSPICIOUS')
            malicious = sum(1 for r in scan_results if r.get('classification') == 'MALICIOUS')
            analyst = sum(1 for r in scan_results if r.get('classification') == 'ANALYST_REQUIRED')
            
            story.append(Paragraph(f"<b>Total URLs Scanned:</b> {total}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Clean:</b> {clean}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Suspicious:</b> {suspicious}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Malicious:</b> {malicious}", self.styles['CustomBody']))
            story.append(Paragraph(f"<b>Analyst Required:</b> {analyst}", self.styles['CustomBody']))
            story.append(Spacer(1, 0.3*inch))
            
            if malicious > 0:
                story.append(Paragraph("High Priority Issues", self.styles['CustomHeading']))
                for result in scan_results:
                    if result.get('classification') == 'MALICIOUS':
                        story.append(Paragraph(f"- {result.get('url')}", self.styles['CustomBody']))
            
            story.append(Spacer(1, 0.5*inch))
            story.append(Paragraph("Generated by Dr. SSM Eye", self.styles['CustomBody']))
            
            doc.build(story)
            
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info("Generated batch summary report")
            return pdf_bytes
        
        except Exception as e:
            logger.error(f"Batch report generation error: {e}")
            raise
    
    def generate_batch_detailed_report(self, scan_results: List[Dict[str, Any]]) -> bytes:
        """
        Generate comprehensive batch report
        
        Args:
            scan_results: List of scan result dictionaries
        
        Returns:
            PDF bytes
        """
        try:
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            story = []
            
            summary_bytes = self.generate_batch_summary_report(scan_results)
            
            for i, result in enumerate(scan_results):
                if i > 0:
                    story.append(PageBreak())
                
                url_report_bytes = self.generate_per_url_report(result)
            
            story.append(Spacer(1, 0.5*inch))
            story.append(Paragraph("End of Report", self.styles['CustomBody']))
            
            doc.build(story)
            
            pdf_bytes = buffer.getvalue()
            buffer.close()
            
            logger.info("Generated batch detailed report")
            return pdf_bytes
        
        except Exception as e:
            logger.error(f"Batch detailed report error: {e}")
            raise